name: CI BUILD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build RabbitMQ Docker image
        run: docker build -t rabbitmq-test .

      - name: Run RabbitMQ container
        run: |
          docker run -d --name rabbitmq-test \
            -e RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_PASS }} \
            -e RABBITMQ_DEFAULT_VHOST=${{ secrets.RABBITMQ_VHOST }} \
            -p 5672:5672 -p 15672:15672 rabbitmq-test
          sleep 10
          docker ps
          docker stop rabbitmq-test
          docker rm rabbitmq-test
